import localFont from "next/font/local";

import {Inter, Outfit, Poppins} from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs";
import Provider from './Provider'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const inter = Outfit({subsets: ["latin"]});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}){
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
          <Provider>
           {children}
           </Provider>
      </body>
      </html>
    </ClerkProvider>
  )
}